version: "3.9"
services:
  server:
    container_name: aid-backend
    build: ./app/backend
    restart: unless-stopped
    ports:
      - 3022:3020
    volumes:
      - ./app/backend:/usr/src/app
    depends_on:
      - mongodb
  vue:
    container_name: aid-frontend
    build: ./app/frontend
    restart: unless-stopped
    ports:
      - 3011:8020
    volumes:
      - ./app/frontend:/usr/src/app
    depends_on:
      - mongodb
  mongodb:
    hostname: mongodb
    image: mongo:5.0.14
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    # command: bash -c "mongorestore -h=mongodb:27017 -u=admin -p=password --authenticationDatabase=admin /data/db/mongodump-v1/"
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8080:8081
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    container_name: mongo_express
