export const zhuanhuan = {
    OTLosses: "Overtime losses",
    OTWins: "Overtime Wins",
    avgPointsAgainst: "Average Points Opposite Get",
    avgPointsFor: "Average Points Get",
    differential: "Differential",
    divisionWinPercent: "Division Win Percent",
    gamesBehind: "Game Behind",
    gamesPlayed: "Games Played",
    leagueWinPercent: "League Wining Percent",
    losses: "Losses",
    playoffSeed: "Playoff Seed No.",
    points: "Points",
    pointsAgainst: "Points Opposite Get",
    pointsFor: "Points Get",
    streak: "Streak",
    ties: "Ties",
    winPercent: "Wining Percent",
    wins: "Wins",
}
